export const STRINGS = {
  APP_NAME: 'VI Uploader App',
  SPLASH: {
    LOADING: 'Initializing...',
  },
  LOGIN: {
    EMAIL: 'test@gmail.com',
    PASSWORD: 'Test@123',
    TITLE: 'Welcome Back',
    SUBTITLE: 'Please sign in to continue',
    EMAIL_PLACEHOLDER: 'Enter your email',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    FORGOT_PASSWORD: 'Forgot Password?',
    BUTTON: 'Login',
    ERROR_EMPTY: 'Please enter both email and password.',
    ERROR_INVALID_EMAIL: 'Please enter a valid email address.',
    AUTH_ERROR: 'Invalid email or password',
    AUTH_STATUS_ERROR: 'Failed to check auth status',
    ERROR_EMPTY_EMAIL: 'Please enter your email',
    ERROR_EMPTY_PASSWORD: 'Please enter your password',
    ERROR_INVALID_PASSWORD: 'Password must contain uppercase, lowercase, number and special character',
  },
  DASHBOARD: {
    TITLE: 'Dashboard',
    SCREEN_NAME: 'Dashboard Screen',
    EXIT_TITLE: 'Exit App',
    EXIT_MESSAGE: 'Do you want to close the application?',
  },
  NAV: {
    HOME: 'Home',
    LIST: 'List',
    LOGOUT: 'Logout',
    BACK: 'Back',
    DONE: 'Done',
    ADD_IMAGE: 'Add Image',
    ADD_VIDEO: 'Add Video',
  },
  LIST: {
    TITLE: 'Media List',
    EMPTY: 'No media found',
    DELETE: {
      TITLE: 'Delete Media',
      MESSAGE: 'Are you sure you want to delete this item?',
      CONFIRM: 'Yes',
    },
  },
  ADD_VIDEO: {
    TITLE: 'Add Video',
    CAPTURE: 'Capture Video',
    SELECT: 'Select From Gallery',
    SIZE_ERROR: 'Video size exceeds the limit (max 1GB).',
    FORMAT_ERROR: 'Invalid video format. Please select an MP4, MOV, MKV or HEVC video.',
    NO_VIDEO: 'Please select video',
    UPLOAD: 'Upload Video',
    DESCRIPTION_PLACEHOLDER: 'Enter video description...',
    DEFAULT_SIZE: '10',
    MB: ' MB',
    SIZE_UNKNOWN: 'Size Unknown',
    DEFAULT_FILENAME: 'video.mp4',
    ERROR_DESCRIPTION: 'Please enter a description',
    CHANGE: 'Update From Gallery',
  },
  ADD_PHOTO: {
    TITLE: 'Add Photo',
    CAPTURE: 'Capture',
    SELECT: 'Gallery',
    SIZE_ERROR: 'Photo size exceeds the limit (max 100MB).',
    FORMAT_ERROR: 'Invalid photo format. Please select a JPG, PNG, HEIC or HEIF image.',
    NO_PHOTO: 'Please select photo',
    UPLOAD: 'Upload Photo',
    DESCRIPTION_PLACEHOLDER: 'Enter photo description...',
    DEFAULT_SIZE: '0.5',
    MB: ' MB',
    ERROR_DESCRIPTION: 'Please enter a description',
  },
  UPLOAD: {
    TITLE: 'Upload Media',
    PROGRESS: 'Uploading...',
    SUCCESS: 'Upload Successful!',
    SUCCESS_SUB: 'Your media has been uploaded successfully.',
    FAILURE: 'Upload Failed. Please try again.',
    FAILURE_TITLE: 'Upload Failed',
    CANCELLED_TITLE: 'Upload Cancelled',
    CANCELLED_SUB: 'You cancelled the upload process.',
    RESUME: 'Resume Upload',
    BUTTON_RETRY: 'Retry',
    BUTTON_CANCEL: 'Cancel',
    DEFAULT_TITLE: 'Media Upload',
    DEFAULT_SIZE: '0 MB',
  },
  PERMISSIONS: {
    DENIED_TITLE: 'Permission Denied',
    DENIED_MSG: 'Please grant permission to access ',
    CAMERA_TITLE: 'Camera Permission',
    CAMERA_MSG: 'We need access to your camera to take photos.',
    PHOTO_TITLE: 'Photo Access Permission',
    PHOTO_MSG: 'We need access to your photos to upload them.',
    VIDEO_TITLE: 'Video Access Permission',
    VIDEO_MSG: 'We need access to your videos to upload them.',
    STORAGE_TITLE: 'Storage Permission',
    STORAGE_MSG: 'We need access to your storage to upload media.',
  },
  COMMON: {
    OK: 'OK',
    YES: 'Yes',
    CANCEL: 'No',
    ASK_ME_LATER: 'Ask Me Later',
    ERROR: 'Error',
    CAMERA_LAUNCH_ERROR: 'Failed to launch camera',
    GALLERY_LAUNCH_ERROR: 'Failed to launch gallery',
  },
  SCREEN_NAMES: {
    LOGIN: 'Login',
    DASHBOARD: 'Dashboard',
    LIST: 'List',
    ADD_VIDEO: 'AddVideo',
    ADD_PHOTO: 'AddPhoto',
    UPLOAD_SCREEN: 'UploadScreen',
  },
  MEDIA_TYPES: {
    VIDEO: 'video',
    PHOTO: 'photo',
  },
};

